server:
  port: 8080

app:
  integration:
    ml:
      # URL onde o teu servidor Flask (Python) está a correr
      url: "http://127.0.0.1:5000/predict"
      # Ponto de corte para decidir se está atrasado (0.5 = 50%)
      threshold-prob: 0.5

    clima:
      # URL da API StormGlass
      url: "https://api.stormglass.io/v2/weather/point"

      key: "${CLIMA_API_KEY}"
      coords:
        # Coordenadas do Aeroporto do Galeão (GIG)
        gig-lat: -22.81
        gig-lon: -43.24

    noticias:
      # URL para simulação de trânsito
      url: "http://localhost:8080/api/noticias"